rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
 path('', views.index, name='index'),
 path('rango/', include('rango.urls')),
 # The above maps any URLs starting with rango/ to be handled by rango.
 path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
 
class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title
    
class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page,Category
from django.contrib.auth.models import User
from rango.models import UserProfile

class CategoryForm(forms.ModelForm):
    name =forms.CharField(max_length=128, help_text="Please enter the category name.")
    views =forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    likes =forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    slug =forms.CharField(widget=forms.HiddenInput(),required=False)

    #An inline class to provide additional information on the form.
    class Meta:
        #Provide an association between the Model Form and a model
        model=Category
        fields =('name',)

class PageForm(forms.ModelForm):
    title =forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url =forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views =forms.IntegerField(widget=forms.HiddenInput(),initial=0)

    class Meta:
       #Provide an association between the Model Form and a model
        model=Page

        #What fields do we want to include in our form?
        #This way we don't need every field in the model present.
        #Some fields may allow NULL values; we may not want to include them.
        #Here, weare hiding the foreign key.
        #we can either exclude the category field from the form,
        exclude= ('category',)
        #or specify the fields to include(don't include the category field).
        #fields=('title','url','views')

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        return cleaned_data
    
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
from rango.models import Category
from rango.models import Page
from rango.forms import CategoryForm
from django.shortcuts import redirect
from rango.forms import PageForm
from rango.forms import UserForm,UserProfileForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime

def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    top_pages = Page.objects.order_by('-views')[:5]

    visitor_cookie_handler(request)  # Call the function to handle visits cookie

    context_dict = {
        'boldmessage': 'Crunchy, creamy, cookie, candy, cupcake!',
        'categories': category_list,
        'top_pages': top_pages,
    }

    return render(request, 'rango/index.html', context_dict)


def about(request):
    print(request.method)
    print(request.user)
    # Call the visitor_cookie_handler function to handle the visit count cookie
    visitor_cookie_handler(request)

    # Get the visit count from the session
    visits = request.session['visits']

    # Render the About page template with the visit count
    return render(request, 'rango/about.html', {'visits': visits})


@login_required
def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = []

    return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('rango:index'))
        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        return redirect('/rango/')

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            page = form.save(commit=False)
            page.category = category
            page.views = 0
            page.save()
            return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            context_dict = {'form': form, 'category': category, 'errors': form.errors}
            return render(request, 'rango/add_page.html', context=context_dict)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST, files=request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)  # Ensure the password is hashed
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'rango/register.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        # We use request.POST.get('<variable>') as opposed
        # to request.POST['<variable>'], because the
        # request.POST.get('<variable>') returns None if the
        # value does not exist, while request.POST['<variable>']
        # will raise a KeyError exception.
        username = request.POST.get('username')
        password = request.POST.get('password')
        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)
        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your Rango account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    # The request is not a HTTP POST, so display the login form.

    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'rango/login.html')
    
def some_view(request):
    if request.user.is_authenticated:
        return HttpResponse("You are logged in.")
    else:
        return HttpResponse("You are not logged in.")
    
@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')


# Use the login_required() decorator to ensure only those logged in can
# access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return redirect(reverse('rango:index'))

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], "%Y-%m-%d %H:%M:%S")

    # Update the cookie only if it's been more than a day since the last visit
    if (datetime.now() - last_visit_time).days > 0:
        visits += 1
        request.session['last_visit'] = str(datetime.now())
        request.session['visits'] = visits  # Update the session with the new value
    else:
        request.session['last_visit'] = last_visit_cookie
        request.session['visits'] = visits  # Set the session with the existing value

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}
    <h1>About Rango</h1>
    <div>
        <p>This tutorial has been put together by Robbie Copeland.</p>
    </div>

    <div>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
    </div>

    <div>
        <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat." />
    </div>

    <div>
        <p>Visits: {{ visits }}</p>
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
    <h1>Add a Category</h1>
    <div>
        <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Category" />
        </form>
    </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}
    <h1>Add a Page</h1>
    <div>
        <form id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Add Page" />
        </form>

        {% if not user.is_authenticated %}
            <p>The specified category does not exist.</p>
        {% endif %}
    </div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}

<html>
<head lang="en">
    <meta charset="UTF-8" />
    <title>Rango -
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>
</head>
<body>
    <hr>
    <div>
        {% block sidebar_block %}
        {% get_category_list category %}
        {% endblock %}
    </div>
    <hr/>
    <div>
        <ul>
            {% if user.is_authenticated %}
                <!-- Show these links when the user is logged in -->
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'rango:logout' %}">Logout</a></li>
                <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
            {% else %}
                <!-- Show these links when the user is NOT logged in -->
                <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
                <li><a href="{% url 'rango:login' %}">Login</a></li>
            {% endif %}
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Index</a></li>
        </ul>
    </div>
    {% block body_block %}
    {% endblock %}
</body>
</html>

templates/rango/categories.html
<ul>
    {% for c in categories %}
        {% if c == current_category %}
            <li>
                <strong>
                    <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                </strong>
            </li>
        {% else %}
            <li>
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
            </li>
        {% endif %}
    {% endfor %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}

        <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br />
    {% else %}
        The specified category does not exist.
    {% endif %}
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        {% if user.is_authenticated %}
            howdy {{ user.username }}!
        {% else %}
            hey there partner!
        {% endif %}
        <br />
        <strong>{{ boldmessage }}</strong><br />
    </div>

    <div>
        {% if categories %}
            <h2>Categories</h2>
            <ul>
                {% for category in categories %}
                    <li>
                        <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No categories present.</p>
        {% endif %}
    </div>

    <div id="pages">
        {% if top_pages %}
            <h2>Most Viewed Pages</h2>
            <ul>
                {% for page in top_pages %}
                    <li>
                        <a href="{{ page.url }}" target="_blank">{{ page.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No pages present.</p>
        {% endif %}
    </div>

    <div>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
    </div>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" />
    <br />
    <input type="submit" value="submit" />
</form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Register for Rango</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
    {% else %}
        Rango says: <strong>register here!</strong><br />
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- Display each form -->
            <p><label for="id_username">Username:</label> <input type="text" name="username" required id="id_username"></p>
            <p><label for="id_password">Password:</label> <input type="password" name="password" required id="id_password"></p>

            {% if user_form.errors %}
                <ul class="errorlist">
                    {% for field in user_form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            {% endif %}

            {{ profile_form.as_p }}

            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
    <h1>Restricted Page</h1>
    <p>This page is restricted to registered users only. Please
        <a href="{% url 'rango:login' %}">login</a> or
        <a href="{% url 'rango:register' %}">register</a> to access this page.</p>
{% endblock %}